// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CtlMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "./network/ctl_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Network {
class CtlMessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CtlMessage> {
} _CtlMessage_default_instance_;

namespace protobuf_CtlMessage_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtlMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtlMessage, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtlMessage, direction_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtlMessage, ctl_type_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CtlMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CtlMessage_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "CtlMessage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _CtlMessage_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CtlMessage_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020CtlMessage.proto\022\007Network\"\305\001\n\nCtlMessa"
      "ge\022\r\n\005value\030\001 \001(\005\0220\n\tdirection\030\002 \001(\0162\035.N"
      "etwork.CtlMessage.Direction\022-\n\010ctl_type\030"
      "\003 \001(\0162\033.Network.CtlMessage.CtlType\"\031\n\tDi"
      "rection\022\005\n\001X\020\000\022\005\n\001Y\020\001\",\n\007CtlType\022\010\n\004STOP"
      "\020\000\022\013\n\007VEHICLE\020\001\022\n\n\006CAMERA\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 235);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CtlMessage.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_CtlMessage_2eproto

const ::google::protobuf::EnumDescriptor* CtlMessage_Direction_descriptor() {
  protobuf_CtlMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CtlMessage_2eproto::file_level_enum_descriptors[0];
}
bool CtlMessage_Direction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CtlMessage_Direction CtlMessage::X;
const CtlMessage_Direction CtlMessage::Y;
const CtlMessage_Direction CtlMessage::Direction_MIN;
const CtlMessage_Direction CtlMessage::Direction_MAX;
const int CtlMessage::Direction_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* CtlMessage_CtlType_descriptor() {
  protobuf_CtlMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CtlMessage_2eproto::file_level_enum_descriptors[1];
}
bool CtlMessage_CtlType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CtlMessage_CtlType CtlMessage::STOP;
const CtlMessage_CtlType CtlMessage::VEHICLE;
const CtlMessage_CtlType CtlMessage::CAMERA;
const CtlMessage_CtlType CtlMessage::CtlType_MIN;
const CtlMessage_CtlType CtlMessage::CtlType_MAX;
const int CtlMessage::CtlType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CtlMessage::kValueFieldNumber;
const int CtlMessage::kDirectionFieldNumber;
const int CtlMessage::kCtlTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CtlMessage::CtlMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CtlMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Network.CtlMessage)
}
CtlMessage::CtlMessage(const CtlMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&value_, &from.value_,
    reinterpret_cast<char*>(&ctl_type_) -
    reinterpret_cast<char*>(&value_) + sizeof(ctl_type_));
  // @@protoc_insertion_point(copy_constructor:Network.CtlMessage)
}

void CtlMessage::SharedCtor() {
  ::memset(&value_, 0, reinterpret_cast<char*>(&ctl_type_) -
    reinterpret_cast<char*>(&value_) + sizeof(ctl_type_));
  _cached_size_ = 0;
}

CtlMessage::~CtlMessage() {
  // @@protoc_insertion_point(destructor:Network.CtlMessage)
  SharedDtor();
}

void CtlMessage::SharedDtor() {
}

void CtlMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CtlMessage::descriptor() {
  protobuf_CtlMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CtlMessage_2eproto::file_level_metadata[0].descriptor;
}

const CtlMessage& CtlMessage::default_instance() {
  protobuf_CtlMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

CtlMessage* CtlMessage::New(::google::protobuf::Arena* arena) const {
  CtlMessage* n = new CtlMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CtlMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Network.CtlMessage)
  ::memset(&value_, 0, reinterpret_cast<char*>(&ctl_type_) -
    reinterpret_cast<char*>(&value_) + sizeof(ctl_type_));
}

bool CtlMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Network.CtlMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 value = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Network.CtlMessage.Direction direction = 2;
      case 2: {
        if (tag == 16u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_direction(static_cast< ::Network::CtlMessage_Direction >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Network.CtlMessage.CtlType ctl_type = 3;
      case 3: {
        if (tag == 24u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ctl_type(static_cast< ::Network::CtlMessage_CtlType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Network.CtlMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Network.CtlMessage)
  return false;
#undef DO_
}

void CtlMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Network.CtlMessage)
  // int32 value = 1;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->value(), output);
  }

  // .Network.CtlMessage.Direction direction = 2;
  if (this->direction() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->direction(), output);
  }

  // .Network.CtlMessage.CtlType ctl_type = 3;
  if (this->ctl_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->ctl_type(), output);
  }

  // @@protoc_insertion_point(serialize_end:Network.CtlMessage)
}

::google::protobuf::uint8* CtlMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Network.CtlMessage)
  // int32 value = 1;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->value(), target);
  }

  // .Network.CtlMessage.Direction direction = 2;
  if (this->direction() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->direction(), target);
  }

  // .Network.CtlMessage.CtlType ctl_type = 3;
  if (this->ctl_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->ctl_type(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Network.CtlMessage)
  return target;
}

size_t CtlMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Network.CtlMessage)
  size_t total_size = 0;

  // int32 value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value());
  }

  // .Network.CtlMessage.Direction direction = 2;
  if (this->direction() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->direction());
  }

  // .Network.CtlMessage.CtlType ctl_type = 3;
  if (this->ctl_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ctl_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CtlMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Network.CtlMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CtlMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CtlMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Network.CtlMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Network.CtlMessage)
    MergeFrom(*source);
  }
}

void CtlMessage::MergeFrom(const CtlMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Network.CtlMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.value() != 0) {
    set_value(from.value());
  }
  if (from.direction() != 0) {
    set_direction(from.direction());
  }
  if (from.ctl_type() != 0) {
    set_ctl_type(from.ctl_type());
  }
}

void CtlMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Network.CtlMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CtlMessage::CopyFrom(const CtlMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Network.CtlMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CtlMessage::IsInitialized() const {
  return true;
}

void CtlMessage::Swap(CtlMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CtlMessage::InternalSwap(CtlMessage* other) {
  std::swap(value_, other->value_);
  std::swap(direction_, other->direction_);
  std::swap(ctl_type_, other->ctl_type_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CtlMessage::GetMetadata() const {
  protobuf_CtlMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CtlMessage_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CtlMessage

// int32 value = 1;
void CtlMessage::clear_value() {
  value_ = 0;
}
::google::protobuf::int32 CtlMessage::value() const {
  // @@protoc_insertion_point(field_get:Network.CtlMessage.value)
  return value_;
}
void CtlMessage::set_value(::google::protobuf::int32 value) {

  value_ = value;
  // @@protoc_insertion_point(field_set:Network.CtlMessage.value)
}

// .Network.CtlMessage.Direction direction = 2;
void CtlMessage::clear_direction() {
  direction_ = 0;
}
::Network::CtlMessage_Direction CtlMessage::direction() const {
  // @@protoc_insertion_point(field_get:Network.CtlMessage.direction)
  return static_cast< ::Network::CtlMessage_Direction >(direction_);
}
void CtlMessage::set_direction(::Network::CtlMessage_Direction value) {

  direction_ = value;
  // @@protoc_insertion_point(field_set:Network.CtlMessage.direction)
}

// .Network.CtlMessage.CtlType ctl_type = 3;
void CtlMessage::clear_ctl_type() {
  ctl_type_ = 0;
}
::Network::CtlMessage_CtlType CtlMessage::ctl_type() const {
  // @@protoc_insertion_point(field_get:Network.CtlMessage.ctl_type)
  return static_cast< ::Network::CtlMessage_CtlType >(ctl_type_);
}
void CtlMessage::set_ctl_type(::Network::CtlMessage_CtlType value) {

  ctl_type_ = value;
  // @@protoc_insertion_point(field_set:Network.CtlMessage.ctl_type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Network

// @@protoc_insertion_point(global_scope)
